package de.codevoid.andremote2

import android.view.KeyEvent

object KeyEventCodes {

    data class KeyCodeEntry(val code: Int, val name: String)

    val keyCodes: List<KeyCodeEntry> = listOf(
        KeyCodeEntry(KeyEvent.KEYCODE_DPAD_UP, "KEYCODE_DPAD_UP"),
        KeyCodeEntry(KeyEvent.KEYCODE_DPAD_DOWN, "KEYCODE_DPAD_DOWN"),
        KeyCodeEntry(KeyEvent.KEYCODE_DPAD_LEFT, "KEYCODE_DPAD_LEFT"),
        KeyCodeEntry(KeyEvent.KEYCODE_DPAD_RIGHT, "KEYCODE_DPAD_RIGHT"),
        KeyCodeEntry(KeyEvent.KEYCODE_DPAD_CENTER, "KEYCODE_DPAD_CENTER"),
        KeyCodeEntry(KeyEvent.KEYCODE_ENTER, "KEYCODE_ENTER"),
        KeyCodeEntry(KeyEvent.KEYCODE_ESCAPE, "KEYCODE_ESCAPE"),
        KeyCodeEntry(KeyEvent.KEYCODE_BACK, "KEYCODE_BACK"),
        KeyCodeEntry(KeyEvent.KEYCODE_HOME, "KEYCODE_HOME"),
        KeyCodeEntry(KeyEvent.KEYCODE_MENU, "KEYCODE_MENU"),
        KeyCodeEntry(KeyEvent.KEYCODE_TAB, "KEYCODE_TAB"),
        KeyCodeEntry(KeyEvent.KEYCODE_SPACE, "KEYCODE_SPACE"),
        KeyCodeEntry(KeyEvent.KEYCODE_DEL, "KEYCODE_DEL"),
        KeyCodeEntry(KeyEvent.KEYCODE_FORWARD_DEL, "KEYCODE_FORWARD_DEL"),
        KeyCodeEntry(KeyEvent.KEYCODE_PAGE_UP, "KEYCODE_PAGE_UP"),
        KeyCodeEntry(KeyEvent.KEYCODE_PAGE_DOWN, "KEYCODE_PAGE_DOWN"),
        KeyCodeEntry(KeyEvent.KEYCODE_MOVE_HOME, "KEYCODE_MOVE_HOME"),
        KeyCodeEntry(KeyEvent.KEYCODE_MOVE_END, "KEYCODE_MOVE_END"),
        KeyCodeEntry(KeyEvent.KEYCODE_VOLUME_UP, "KEYCODE_VOLUME_UP"),
        KeyCodeEntry(KeyEvent.KEYCODE_VOLUME_DOWN, "KEYCODE_VOLUME_DOWN"),
        KeyCodeEntry(KeyEvent.KEYCODE_VOLUME_MUTE, "KEYCODE_VOLUME_MUTE"),
        KeyCodeEntry(KeyEvent.KEYCODE_MEDIA_PLAY, "KEYCODE_MEDIA_PLAY"),
        KeyCodeEntry(KeyEvent.KEYCODE_MEDIA_PAUSE, "KEYCODE_MEDIA_PAUSE"),
        KeyCodeEntry(KeyEvent.KEYCODE_MEDIA_PLAY_PAUSE, "KEYCODE_MEDIA_PLAY_PAUSE"),
        KeyCodeEntry(KeyEvent.KEYCODE_MEDIA_STOP, "KEYCODE_MEDIA_STOP"),
        KeyCodeEntry(KeyEvent.KEYCODE_MEDIA_NEXT, "KEYCODE_MEDIA_NEXT"),
        KeyCodeEntry(KeyEvent.KEYCODE_MEDIA_PREVIOUS, "KEYCODE_MEDIA_PREVIOUS"),
        KeyCodeEntry(KeyEvent.KEYCODE_MEDIA_REWIND, "KEYCODE_MEDIA_REWIND"),
        KeyCodeEntry(KeyEvent.KEYCODE_MEDIA_FAST_FORWARD, "KEYCODE_MEDIA_FAST_FORWARD"),
        KeyCodeEntry(KeyEvent.KEYCODE_CHANNEL_UP, "KEYCODE_CHANNEL_UP"),
        KeyCodeEntry(KeyEvent.KEYCODE_CHANNEL_DOWN, "KEYCODE_CHANNEL_DOWN"),
        KeyCodeEntry(KeyEvent.KEYCODE_BUTTON_A, "KEYCODE_BUTTON_A"),
        KeyCodeEntry(KeyEvent.KEYCODE_BUTTON_B, "KEYCODE_BUTTON_B"),
        KeyCodeEntry(KeyEvent.KEYCODE_BUTTON_X, "KEYCODE_BUTTON_X"),
        KeyCodeEntry(KeyEvent.KEYCODE_BUTTON_Y, "KEYCODE_BUTTON_Y"),
        KeyCodeEntry(KeyEvent.KEYCODE_BUTTON_L1, "KEYCODE_BUTTON_L1"),
        KeyCodeEntry(KeyEvent.KEYCODE_BUTTON_R1, "KEYCODE_BUTTON_R1"),
        KeyCodeEntry(KeyEvent.KEYCODE_BUTTON_L2, "KEYCODE_BUTTON_L2"),
        KeyCodeEntry(KeyEvent.KEYCODE_BUTTON_R2, "KEYCODE_BUTTON_R2"),
        KeyCodeEntry(KeyEvent.KEYCODE_BUTTON_START, "KEYCODE_BUTTON_START"),
        KeyCodeEntry(KeyEvent.KEYCODE_BUTTON_SELECT, "KEYCODE_BUTTON_SELECT"),
        KeyCodeEntry(KeyEvent.KEYCODE_BUTTON_THUMBL, "KEYCODE_BUTTON_THUMBL"),
        KeyCodeEntry(KeyEvent.KEYCODE_BUTTON_THUMBR, "KEYCODE_BUTTON_THUMBR"),
        KeyCodeEntry(KeyEvent.KEYCODE_0, "KEYCODE_0"),
        KeyCodeEntry(KeyEvent.KEYCODE_1, "KEYCODE_1"),
        KeyCodeEntry(KeyEvent.KEYCODE_2, "KEYCODE_2"),
        KeyCodeEntry(KeyEvent.KEYCODE_3, "KEYCODE_3"),
        KeyCodeEntry(KeyEvent.KEYCODE_4, "KEYCODE_4"),
        KeyCodeEntry(KeyEvent.KEYCODE_5, "KEYCODE_5"),
        KeyCodeEntry(KeyEvent.KEYCODE_6, "KEYCODE_6"),
        KeyCodeEntry(KeyEvent.KEYCODE_7, "KEYCODE_7"),
        KeyCodeEntry(KeyEvent.KEYCODE_8, "KEYCODE_8"),
        KeyCodeEntry(KeyEvent.KEYCODE_9, "KEYCODE_9"),
        KeyCodeEntry(KeyEvent.KEYCODE_A, "KEYCODE_A"),
        KeyCodeEntry(KeyEvent.KEYCODE_B, "KEYCODE_B"),
        KeyCodeEntry(KeyEvent.KEYCODE_C, "KEYCODE_C"),
        KeyCodeEntry(KeyEvent.KEYCODE_D, "KEYCODE_D"),
        KeyCodeEntry(KeyEvent.KEYCODE_E, "KEYCODE_E"),
        KeyCodeEntry(KeyEvent.KEYCODE_F, "KEYCODE_F"),
        KeyCodeEntry(KeyEvent.KEYCODE_G, "KEYCODE_G"),
        KeyCodeEntry(KeyEvent.KEYCODE_H, "KEYCODE_H"),
        KeyCodeEntry(KeyEvent.KEYCODE_I, "KEYCODE_I"),
        KeyCodeEntry(KeyEvent.KEYCODE_J, "KEYCODE_J"),
        KeyCodeEntry(KeyEvent.KEYCODE_K, "KEYCODE_K"),
        KeyCodeEntry(KeyEvent.KEYCODE_L, "KEYCODE_L"),
        KeyCodeEntry(KeyEvent.KEYCODE_M, "KEYCODE_M"),
        KeyCodeEntry(KeyEvent.KEYCODE_N, "KEYCODE_N"),
        KeyCodeEntry(KeyEvent.KEYCODE_O, "KEYCODE_O"),
        KeyCodeEntry(KeyEvent.KEYCODE_P, "KEYCODE_P"),
        KeyCodeEntry(KeyEvent.KEYCODE_Q, "KEYCODE_Q"),
        KeyCodeEntry(KeyEvent.KEYCODE_R, "KEYCODE_R"),
        KeyCodeEntry(KeyEvent.KEYCODE_S, "KEYCODE_S"),
        KeyCodeEntry(KeyEvent.KEYCODE_T, "KEYCODE_T"),
        KeyCodeEntry(KeyEvent.KEYCODE_U, "KEYCODE_U"),
        KeyCodeEntry(KeyEvent.KEYCODE_V, "KEYCODE_V"),
        KeyCodeEntry(KeyEvent.KEYCODE_W, "KEYCODE_W"),
        KeyCodeEntry(KeyEvent.KEYCODE_X, "KEYCODE_X"),
        KeyCodeEntry(KeyEvent.KEYCODE_Y, "KEYCODE_Y"),
        KeyCodeEntry(KeyEvent.KEYCODE_Z, "KEYCODE_Z"),
        KeyCodeEntry(KeyEvent.KEYCODE_F1, "KEYCODE_F1"),
        KeyCodeEntry(KeyEvent.KEYCODE_F2, "KEYCODE_F2"),
        KeyCodeEntry(KeyEvent.KEYCODE_F3, "KEYCODE_F3"),
        KeyCodeEntry(KeyEvent.KEYCODE_F4, "KEYCODE_F4"),
        KeyCodeEntry(KeyEvent.KEYCODE_F5, "KEYCODE_F5"),
        KeyCodeEntry(KeyEvent.KEYCODE_F6, "KEYCODE_F6"),
        KeyCodeEntry(KeyEvent.KEYCODE_F7, "KEYCODE_F7"),
        KeyCodeEntry(KeyEvent.KEYCODE_F8, "KEYCODE_F8"),
        KeyCodeEntry(KeyEvent.KEYCODE_F9, "KEYCODE_F9"),
        KeyCodeEntry(KeyEvent.KEYCODE_F10, "KEYCODE_F10"),
        KeyCodeEntry(KeyEvent.KEYCODE_F11, "KEYCODE_F11"),
        KeyCodeEntry(KeyEvent.KEYCODE_F12, "KEYCODE_F12"),
        KeyCodeEntry(KeyEvent.KEYCODE_POWER, "KEYCODE_POWER"),
        KeyCodeEntry(KeyEvent.KEYCODE_CAMERA, "KEYCODE_CAMERA"),
        KeyCodeEntry(KeyEvent.KEYCODE_SEARCH, "KEYCODE_SEARCH"),
        KeyCodeEntry(KeyEvent.KEYCODE_NAVIGATE_PREVIOUS, "KEYCODE_NAVIGATE_PREVIOUS"),
        KeyCodeEntry(KeyEvent.KEYCODE_NAVIGATE_NEXT, "KEYCODE_NAVIGATE_NEXT"),
        KeyCodeEntry(KeyEvent.KEYCODE_NAVIGATE_IN, "KEYCODE_NAVIGATE_IN"),
        KeyCodeEntry(KeyEvent.KEYCODE_NAVIGATE_OUT, "KEYCODE_NAVIGATE_OUT"),
        KeyCodeEntry(KeyEvent.KEYCODE_PROG_RED, "KEYCODE_PROG_RED"),
        KeyCodeEntry(KeyEvent.KEYCODE_PROG_GREEN, "KEYCODE_PROG_GREEN"),
        KeyCodeEntry(KeyEvent.KEYCODE_PROG_YELLOW, "KEYCODE_PROG_YELLOW"),
        KeyCodeEntry(KeyEvent.KEYCODE_PROG_BLUE, "KEYCODE_PROG_BLUE"),
        KeyCodeEntry(KeyEvent.KEYCODE_INFO, "KEYCODE_INFO"),
        KeyCodeEntry(KeyEvent.KEYCODE_GUIDE, "KEYCODE_GUIDE"),
        KeyCodeEntry(KeyEvent.KEYCODE_DVR, "KEYCODE_DVR"),
        KeyCodeEntry(KeyEvent.KEYCODE_TV, "KEYCODE_TV"),
        KeyCodeEntry(KeyEvent.KEYCODE_SETTINGS, "KEYCODE_SETTINGS"),
        KeyCodeEntry(KeyEvent.KEYCODE_ZOOM_IN, "KEYCODE_ZOOM_IN"),
        KeyCodeEntry(KeyEvent.KEYCODE_ZOOM_OUT, "KEYCODE_ZOOM_OUT")
    ).sortedBy { it.code }

    val displayNames: List<String> = keyCodes.map { "${it.code} - ${it.name}" }

    fun indexOfCode(code: Int): Int {
        val idx = keyCodes.indexOfFirst { it.code == code }
        return if (idx >= 0) idx else 0
    }

    fun codeAtIndex(index: Int): Int {
        return keyCodes.getOrElse(index) { keyCodes[0] }.code
    }
}
